### ISSUE TITLE
Contribute back to NF-Core

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/phaseimpute#112]
### Description of feature

Some of the subworkflows developped and modules modification done in phaseimpute might be interesting to add to nf-core and others might already be present and might need update

```[tasklist]
### Tasks
- [ ] vcf_split_bcftools to nf-core [#6016](https://github.com/nf-core/modules/pull/6016)
- [ ] vcf_concat_bcftools
- [ ] bam_downsample_samtools [#6019](https://github.com/nf-core/modules/pull/6019)
- [ ] bam_chr_rename_samtools
- [ ] vcf_chr_rename_bcftools
- [ ] vcf_phase_shapeit5
```

**Comment by LouisLeNezet** [comment]
vcf_split_bcftools and chr renaming subworkflows are not needed in nf-core modules repository for the moment.

**Comment by atrigila** [comment]
Several sbwfs are still local: https://github.com/nf-core/phaseimpute/tree/dev/subworkflows/local and they should be migrated to nf-core and then re-imported for better long-term maintenance: 

- bam_chr_rename_samtools
- bam_extract_region_samtools
- vcf_chr_rename_bcftools
- vcf_chunk_glimpse
- vcf_concordance_glimpse2
- vcf_normalize_bcftools
- vcf_sites_extract_bcftools
- vcf_split_bcftools
