### ISSUE TITLE
Correctly separate panel preparation and imputation

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/phaseimpute#29]
### Description of the bug

The panel preparation and the imputation are not yet done separately for glimpse and quilt.
The aim would be to do all the preprocessing in the get_panel sbwf to not have duplicated modules and better readability.

```[tasklist]
### Tasks
- [ ] Chunk panel inside get_panel for glimpse1 and quilt
- [ ] Add normalisation identical for glimpse1 and quilt
- [ ] https://github.com/nf-core/phaseimpute/issues/41
```
