### ISSUE TITLE
Version ready for review v0.99.0

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/phaseimpute#37]
### Description of feature

Before the first release here is the different issues that need to be adressed:

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phaseimpute/issues/36
- [ ] https://github.com/nf-core/phaseimpute/issues/29
- [ ] https://github.com/nf-core/phaseimpute/issues/38
- [ ] https://github.com/nf-core/phaseimpute/issues/42
- [ ] https://github.com/nf-core/phaseimpute/issues/55
- [ ] https://github.com/nf-core/phaseimpute/issues/52
- [ ] https://github.com/nf-core/phaseimpute/issues/53
- [x] Add multiqc new version with graph !
- [ ] https://github.com/nf-core/phaseimpute/issues/120
```

**Comment by atrigila** [comment]
I am closing this issue as all aspects have been addressed.
