### ISSUE TITLE
Include glimpse2 imputation tool 

### ISSUE THREAD

**Issue by atrigila** [nf-core/phaseimpute#39]
### Description of feature

Add `glimpse2` as an alternative imputation tool
```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phaseimpute/issues/45
- [ ] https://github.com/nf-core/phaseimpute/issues/46
- [ ] Add glimpse2 phase method
```
