### ISSUE TITLE
Uniformize tools name

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/phaseimpute#42]
### Description of the bug

We need to normalize the names of tools used such as BCFTOOLS_INDEX.
Same for the use of GAWK.

What can be done:
- All process use twice in subworkflow add "_1/_2" to separate them
- All sbwf names as "input_process_tool"

```[tasklist]
### Tasks
- [x] BCFTOOLS_INDEX
- [x] GAWK
- [x] Channel description
- [x] Align =, : and other punctuation in config files
- [x] Use only one type of quote in config files
- [x] Use params.pipelines_testdata_base_path +
- [x] Call process without main.nf
- [x] All process as main.nf
- [x] Add versions of all tools
```
