### ISSUE TITLE
Add required arguments as external params to start the pipeline

### ISSUE THREAD

**Issue by atrigila** [nf-core/phaseimpute#52]
### Description of feature

Currently, the pipeline requires the channels from `--step panelprep` to run the following modes. To start the pipeline simply from different steps (such as `--step impute`), some files are necessary depending on the tool used (such as `chunks`, `posfile`, `bams` and `panel` ). The bams and panel can be added via a csv with `--input` and `--panel`. We should add the other files as external params.
```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phaseimpute/issues/59
- [ ] https://github.com/nf-core/phaseimpute/issues/57
- [ ] https://github.com/nf-core/phaseimpute/issues/60
- [ ] https://github.com/nf-core/phaseimpute/issues/69
- [ ] https://github.com/nf-core/phaseimpute/issues/72
- [ ] https://github.com/nf-core/phaseimpute/issues/73
- [ ] https://github.com/nf-core/phaseimpute/issues/63
- [ ] https://github.com/nf-core/phaseimpute/issues/77
- [ ] https://github.com/nf-core/phaseimpute/issues/76
```

**Comment by LouisLeNezet** [comment]
For the other files to be added, should we set one per chromosome and add optional column to the panel samplesheet ?

**Comment by atrigila** [comment]
I was thinking them to be samplesheets as well. For instance, `--chunks samplesheet_chunks.csv` where `samplesheet_chunks.csv` would look like: 

```
chr, file
chr1, chunk_file_glimpse1.txt
chr2, chunk_file_glimpse1.txt
```
File could be a `.txt` or `.bin`. 

`Glimpse1` and `QUILT` use `.txt` and `Glimpse2` could use `.bin`.

**Comment by atrigila** [comment]
@LouisLeNezet Let's brainstorm potential structures of samplesheets starting from `--steps impute`:

1. `--posfile posfile.csv`

| chr   | file    | sites vcf       |
| ---    | ---   | ---     |
| chr1 | chr1_posfile_stitch.txt | chr1_sites_glimpse.vcf |

`chr` and `file` are mandatory for all pipelines using posfile,
`sites vcf` is only mandatory for `glimpse1`

What should the default structure of the `.txt` file be? Should the `.txt` file be glimpse1 or stitch posfile? What if the user wants to only use stitch? 

2. `--panel panel.csv` (all tools except stitch)

| panel | chr   | file    | index       | hap | legend |
| --- | ---    | ---   | ---     |  ---     |  ---     | 
| 1000G | chr1 | chr1_phased_panel.vcf.gz | chr1_phased_panel.vcf.gz.tbi | chr1_phased_panel.hap | chr1_phased_panel.legend |

`hap` and `legend` are only required in `quilt`.

3. `--chunks chunks.csv`

| panel   | chr    | file       |
| ---    | ---   | ---     |
| 1000G | chr1 | chr1_chunks_glimpse1.txt |

**Comment by LouisLeNezet** [comment]
Hi,
What you suggest is fine for me.
Considering the default structure of the posfile txt file the stitch format seems more appropriate as you suggested.
Also, isn't the `.legend` equivalent to the posfile ?
- `.legend`: CHROM:POS_REF_ALT POS REF ALT
- `.posfile_stitch`: CHROM POS REF ALT
We could simply reformat it, no ?
