### ISSUE TITLE
Future improvement

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/phaseimpute#90]
### Description of feature

It is possible to remove the multiallelic alleles and samples in one step (reduce computation load)
It would be nice to add cram support and to test for the chr prefix present with `samtools header`
```[tasklist]
### Tasks
- [x] Remove samples in one step
- [x] Support for cram
- [x] Test contigs names in alignement file
```
